language: python
sudo: false
branches:
  only:
  - master
install:
- source devtools/travis-ci/install.sh
- export PYTHONUNBUFFERED=true
- if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then openssl aes-256-cbc -K $encrypted_a755ba9fa4fd_key
  -iv $encrypted_a755ba9fa4fd_iv -in oe_license.txt.enc -out $OE_LICENSE -d; fi
- if [ "$TRAVIS_SECURE_ENV_VARS" == false ]; then echo "OpenEye license will not be
  installed in forks."; fi
script:
- conda config --add channels ${ORGNAME}
- conda create --yes -n test python=$python
- source activate test
- pip install --pre -i https://pypi.anaconda.org/openeye/label/beta/simple openeye-toolkits
  && python -c "import openeye; print(openeye.__version__)"
- pip install git+https://github.com/openforcefield/openforcefield.git
- conda build devtools/conda-recipe
- conda install --yes nose nose-timer
- cd devtools && nosetests -vv --nocapture --with-timer $PACKAGENAME && cd ..
env:
  matrix:
  - python=3.5  CONDA_PY=35
  global:
  - ORGNAME="mobleylab"
  - PACKAGENAME="minidrugbank"
  - OE_LICENSE="$HOME/oe_license.txt"
  - OPENEYE_CHANNEL="-i https://pypi.anaconda.org/openeye/channel/main/simple"
  secure: "Uw5sjGT+d6SBJSf8Q6N5BI2o92WnFZiKqhnEIZ7VMCdf4JxF0RNoyC1zqdSxoLVFpigWbVkEbzymExexX3vw1M3dLL8MgbrpZm5y9PEHZKIqixBSwSUUA1IIuynVwldpeejwqPYqUxCH5URlj4bil2htBEvxQzpRb5equ4JuoH/bBLcYtroAXXHMMcpKnlT3zUTH2Dr386HIcEHR4F8Nr1uxL+PQya+m+CTvKFJtCNeZO+/kKTP1oVcD9C1+DJK4hD7B5sMk90rhDr/3GVDAK8BnSzh2iIraHvRyDZCkPzASUO2U0I78IfjD09EXkbReSbIDyqpFCo1UxeheLEpaBCkAQR4fBhxCDTV1F9q1Hnj1p2B3WgARHQB+GRiJg7e/fayvwM3P1fEQkR+kGR0N2UmFFJEqY+69u5KUPmNvalm8emVNnOP6o95CX+cII2eCl02XycR3RRpTXOmyckbsgJzgVM5+DRZx7B35c32fseKV2GSpdERm9mM5ncLQCImveyOu6vm1PSIN0FBnb0B4cMydBgtPjHm4uh0ydb8hRA2mJzmwh6JSbw7n6CWyvo7vuqGoQ/Q9ywVuV1osW0C1E+AKubRzSOdre3m/aDahyFtruOamxfXekVlEY2kudn+B7+do6I1ZTHWNgY2isDDCpDtx8pSi7wagtK1CPbeXdWo="
