language: c
sudo: false

python:
    - "2.7"
    - "3.4"
    - "3.5"

branches:
  only:
    - master

install:
  - source devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true

script:
  # Create and activate test environment
  - conda create --yes -n test python=$python
  - source activate test
  # Install openforcefield tools
  # TODO if changes to openforcefield become less dynamic switch to conda install?
  - pip install git+https://github.com/open-forcefield-group/openforcefield.git
  # Run tests
  - conda install --yes nose nose-timer
  - cd devtools && nosetests -vv --nocapture --with-timer MiniDrugBank && cd ..

