package:
  name: minidrugbank 
  version: 0.0.0

source:
  path: ../..

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - nose
    - nose-timer
  imports:
    - minidrugbank

about:
  home: https://github.com/open-forcefield-group/minidrugbank
  license: MIT
