package:
  name: minidrugbank 
  version: 0.0.0

source:
  path: ../..

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - nose
    - nose-timer

about:
  home: https://github.com/open-forcefield-group/minidrugbank
  license: MIT
